import { State } from '../types';

export const initialState: State = {
  days: 31,
  currentDay: 1,
  debt: 2000,
  cash: 2000,
  interestRate: 0.2,
  // Empty until the run starts — day-1 prices roll at START_RUN, so a
  // "click to start" prompt would describe a state the player never
  // sees (owner call, copy review 2026-07-17)
  log: [],
  highScore: null,
  modalOpen: true,
  gameOver: null,
  stats: {
    peakNetWorth: 0,
    totalTrades: 0,
    bestTradeProfit: 0,
  },
  seed: 0,
  rngState: 0,
  mode: 'Normal',
  lowRangePriceChance: 5,
  highRangePriceChance: 94,
  wallet: {
    amount: 0,
    capacity: 100,
    level: 0,
    expansionCost: 50000,
  },
  assets: {
    bitcoin: {
      name: 'Bitcoin',
      symbol: 'BTC',
      wallet: 0,
      averageCost: 0,
      totalCost: 0,
      active: true,
      range: {
        low: [3500, 4550],
        mid: [9000, 65000],
        high: [105000, 125000],
        moon: [300000, 700000],
      },
      price: 0,
      previousPrice: 0,
    },
    ethereum: {
      name: 'Ethereum',
      symbol: 'ETH',
      wallet: 0,
      averageCost: 0,
      totalCost: 0,
      active: true,
      range: {
        low: [175, 350],
        mid: [700, 4800],
        high: [10000, 12500],
        moon: [45000, 99999],
      },
      price: 0,
      previousPrice: 0,
    },
    litecoin: {
      name: 'Litecoin',
      symbol: 'LTC',
      wallet: 0,
      averageCost: 0,
      totalCost: 0,
      active: true,
      range: {
        low: [20, 45],
        mid: [90, 630],
        high: [1200, 1500],
        moon: [4500, 8500],
      },
      price: 0,
      previousPrice: 0,
    },
    solana: {
      name: 'Solana',
      symbol: 'SOL',
      wallet: 0,
      averageCost: 0,
      totalCost: 0,
      active: true,
      range: {
        low: [1, 5],
        mid: [20, 110],
        high: [200, 580],
        moon: [1000, 3000],
      },
      price: 0,
      previousPrice: 0,
    },
    dogecoin: {
      name: 'Dogecoin',
      symbol: 'DOGE',
      wallet: 0,
      averageCost: 0,
      totalCost: 0,
      active: true,
      range: {
        low: [1, 3],
        mid: [5, 25],
        high: [35, 75],
        moon: [150, 250],
      },
      price: 0,
      previousPrice: 0,
    },
  },
};
